[package]
name = "rosalind2"
version = "0.1.0"
authors = ["Tamer Gur"]
edition = "2018"

[dependencies]
bio = "*"
indextree = "4.0.0"
prettytable-rs = "^0.8"
rand = "0.7"
petgraph="0.5"
taxonomy="0.4.1"