use bio::io::fasta;
use rosalind2::alignment::ctea;
use rosalind2::alignment::edta;
use rosalind2::alignment::gaff;
use rosalind2::alignment::gcon;
use rosalind2::alignment::glob;
use rosalind2::alignment::ksim;
use rosalind2::alignment::laff;
use rosalind2::alignment::loca;
use rosalind2::alignment::mgap;
use rosalind2::alignment::mult;
use rosalind2::alignment::oap;
use rosalind2::alignment::osym;
use rosalind2::alignment::pdst;
use rosalind2::alignment::sims;
use rosalind2::alignment::smgb;
use rosalind2::combinatorics::aspc;
use rosalind2::combinatorics::cat;
use rosalind2::combinatorics::mmch;
use rosalind2::combinatorics::motz;
use rosalind2::combinatorics::sset;
use rosalind2::dynamicp::lcsq;
use rosalind2::graph::inod;
use rosalind2::graph::lrep;
use rosalind2::graph::suff;
use rosalind2::graph::trie;
use rosalind2::sort::hea;
use rosalind2::sort::hs;
use rosalind2::sort::mer;
use rosalind2::string::edit;
use rosalind2::string::itwv;
use rosalind2::string::kmer;
use rosalind2::string::kmp;
use rosalind2::string::lcsq as recursive_lcsq;
use rosalind2::string::lexv;
use rosalind2::string::ling;
use rosalind2::string::mrep;
use rosalind2::string::scsp;

fn main() {
    mer::solve();
}
